// Code generated by protoc-gen-go.
// source: IM.Buddy.proto
// DO NOT EDIT!

/*
Package IM_Buddy is a generated protocol buffer package.

It is generated from these files:
	IM.Buddy.proto

It has these top-level messages:
	IMRecentContactSessionReq
	IMRecentContactSessionRsp
	IMRecentSesAndUnreadCntRsp
	IMUserStatNotify
	IMUsersInfoReq
	IMUsersInfoRsp
	IMRemoveSessionReq
	IMRemoveSessionRsp
	IMAllUserReq
	IMAllUserRsp
	IMUsersStatReq
	IMUsersStatRsp
	IMChangeAvatarReq
	IMChangeAvatarRsp
	IMPCLoginStatusNotify
	IMRemoveSessionNotify
	IMDepartmentReq
	IMDepartmentRsp
*/
package IM_Buddy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import "IMWebServer/models/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type IMRecentContactSessionReq struct {
	// cmd id:		0x0201
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMRecentContactSessionReq) Reset()                    { *m = IMRecentContactSessionReq{} }
func (m *IMRecentContactSessionReq) String() string            { return proto.CompactTextString(m) }
func (*IMRecentContactSessionReq) ProtoMessage()               {}
func (*IMRecentContactSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMRecentContactSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRecentContactSessionRsp struct {
	// cmd id:		0x0202
	UserId             *uint32                             `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ContactSessionList []*IM_BaseDefine.ContactSessionInfo `protobuf:"bytes,2,rep,name=contact_session_list" json:"contact_session_list,omitempty"`
	AttachData         []byte                              `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized   []byte                              `json:"-"`
}

func (m *IMRecentContactSessionRsp) Reset()                    { *m = IMRecentContactSessionRsp{} }
func (m *IMRecentContactSessionRsp) String() string            { return proto.CompactTextString(m) }
func (*IMRecentContactSessionRsp) ProtoMessage()               {}
func (*IMRecentContactSessionRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMRecentContactSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionRsp) GetContactSessionList() []*IM_BaseDefine.ContactSessionInfo {
	if m != nil {
		return m.ContactSessionList
	}
	return nil
}

func (m *IMRecentContactSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRecentSesAndUnreadCntRsp struct {
	// cmd id:		0x0213
	UserId             *uint32                                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ContactSessionList []*IM_BaseDefine.ContactSesAndUnreadCntInfo `protobuf:"bytes,2,rep,name=contact_session_list" json:"contact_session_list,omitempty"`
	UnreadTotalCnt     *uint32                                     `protobuf:"varint,3,req,name=unread_total_cnt" json:"unread_total_cnt,omitempty"`
	AttachData         []byte                                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized   []byte                                      `json:"-"`
}

func (m *IMRecentSesAndUnreadCntRsp) Reset()                    { *m = IMRecentSesAndUnreadCntRsp{} }
func (m *IMRecentSesAndUnreadCntRsp) String() string            { return proto.CompactTextString(m) }
func (*IMRecentSesAndUnreadCntRsp) ProtoMessage()               {}
func (*IMRecentSesAndUnreadCntRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMRecentSesAndUnreadCntRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentSesAndUnreadCntRsp) GetContactSessionList() []*IM_BaseDefine.ContactSesAndUnreadCntInfo {
	if m != nil {
		return m.ContactSessionList
	}
	return nil
}

func (m *IMRecentSesAndUnreadCntRsp) GetUnreadTotalCnt() uint32 {
	if m != nil && m.UnreadTotalCnt != nil {
		return *m.UnreadTotalCnt
	}
	return 0
}

func (m *IMRecentSesAndUnreadCntRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUserStatNotify struct {
	// cmd id:		0x0203
	UserStat         *IM_BaseDefine.UserStat `protobuf:"bytes,1,req,name=user_stat" json:"user_stat,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *IMUserStatNotify) Reset()                    { *m = IMUserStatNotify{} }
func (m *IMUserStatNotify) String() string            { return proto.CompactTextString(m) }
func (*IMUserStatNotify) ProtoMessage()               {}
func (*IMUserStatNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMUserStatNotify) GetUserStat() *IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStat
	}
	return nil
}

type IMUsersInfoReq struct {
	// cmd id:		0x0204
	UserId           *uint32  `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	UserIdList       []uint32 `protobuf:"varint,2,rep,name=user_id_list" json:"user_id_list,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMUsersInfoReq) Reset()                    { *m = IMUsersInfoReq{} }
func (m *IMUsersInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMUsersInfoReq) ProtoMessage()               {}
func (*IMUsersInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IMUsersInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersInfoRsp struct {
	// cmd id:		0x0205
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	UserInfoList     []*IM_BaseDefine.UserInfo `protobuf:"bytes,2,rep,name=user_info_list" json:"user_info_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMUsersInfoRsp) Reset()                    { *m = IMUsersInfoRsp{} }
func (m *IMUsersInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUsersInfoRsp) ProtoMessage()               {}
func (*IMUsersInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMUsersInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoRsp) GetUserInfoList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

func (m *IMUsersInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionReq struct {
	// cmd id:		0x0206
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionReq) Reset()                    { *m = IMRemoveSessionReq{} }
func (m *IMRemoveSessionReq) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionReq) ProtoMessage()               {}
func (*IMRemoveSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMRemoveSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionRsp struct {
	// cmd id:		0x0207
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ResultCode       *uint32                    `protobuf:"varint,2,req,name=result_code" json:"result_code,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,3,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,4,req,name=session_id" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionRsp) Reset()                    { *m = IMRemoveSessionRsp{} }
func (m *IMRemoveSessionRsp) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionRsp) ProtoMessage()               {}
func (*IMRemoveSessionRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMRemoveSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserReq struct {
	// cmd id:		0x0208
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMAllUserReq) Reset()                    { *m = IMAllUserReq{} }
func (m *IMAllUserReq) String() string            { return proto.CompactTextString(m) }
func (*IMAllUserReq) ProtoMessage()               {}
func (*IMAllUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMAllUserReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserRsp struct {
	// cmd id:		0x0209
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LatestUpdateTime *uint32                   `protobuf:"varint,2,req,name=latest_update_time" json:"latest_update_time,omitempty"`
	UserList         []*IM_BaseDefine.UserInfo `protobuf:"bytes,3,rep,name=user_list" json:"user_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMAllUserRsp) Reset()                    { *m = IMAllUserRsp{} }
func (m *IMAllUserRsp) String() string            { return proto.CompactTextString(m) }
func (*IMAllUserRsp) ProtoMessage()               {}
func (*IMAllUserRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMAllUserRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserRsp) GetUserList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *IMAllUserRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatReq struct {
	// cmd id:		0x020a
	UserId           *uint32  `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	UserIdList       []uint32 `protobuf:"varint,2,rep,name=user_id_list" json:"user_id_list,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMUsersStatReq) Reset()                    { *m = IMUsersStatReq{} }
func (m *IMUsersStatReq) String() string            { return proto.CompactTextString(m) }
func (*IMUsersStatReq) ProtoMessage()               {}
func (*IMUsersStatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMUsersStatReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersStatReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatRsp struct {
	// cmd id:		0x020b
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	UserStatList     []*IM_BaseDefine.UserStat `protobuf:"bytes,2,rep,name=user_stat_list" json:"user_stat_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMUsersStatRsp) Reset()                    { *m = IMUsersStatRsp{} }
func (m *IMUsersStatRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUsersStatRsp) ProtoMessage()               {}
func (*IMUsersStatRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMUsersStatRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatRsp) GetUserStatList() []*IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStatList
	}
	return nil
}

func (m *IMUsersStatRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarReq struct {
	// cmd id:		0x020c
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	AvatarUrl        *string `protobuf:"bytes,2,req,name=avatar_url" json:"avatar_url,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeAvatarReq) Reset()                    { *m = IMChangeAvatarReq{} }
func (m *IMChangeAvatarReq) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarReq) ProtoMessage()               {}
func (*IMChangeAvatarReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMChangeAvatarReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarReq) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarRsp struct {
	// cmd id:		0x020d
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code" json:"result_code,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeAvatarRsp) Reset()                    { *m = IMChangeAvatarRsp{} }
func (m *IMChangeAvatarRsp) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarRsp) ProtoMessage()               {}
func (*IMChangeAvatarRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMChangeAvatarRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 只给移动端通知
type IMPCLoginStatusNotify struct {
	// cmd id:		0x020e
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LoginStat        *IM_BaseDefine.UserStatType `protobuf:"varint,2,req,name=login_stat,enum=IM.BaseDefine.UserStatType" json:"login_stat,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMPCLoginStatusNotify) Reset()                    { *m = IMPCLoginStatusNotify{} }
func (m *IMPCLoginStatusNotify) String() string            { return proto.CompactTextString(m) }
func (*IMPCLoginStatusNotify) ProtoMessage()               {}
func (*IMPCLoginStatusNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMPCLoginStatusNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPCLoginStatusNotify) GetLoginStat() IM_BaseDefine.UserStatType {
	if m != nil && m.LoginStat != nil {
		return *m.LoginStat
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

type IMRemoveSessionNotify struct {
	// cmd id:		0x020f
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionNotify) Reset()                    { *m = IMRemoveSessionNotify{} }
func (m *IMRemoveSessionNotify) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionNotify) ProtoMessage()               {}
func (*IMRemoveSessionNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IMRemoveSessionNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type IMDepartmentReq struct {
	// cmd id:		0x0210
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDepartmentReq) Reset()                    { *m = IMDepartmentReq{} }
func (m *IMDepartmentReq) String() string            { return proto.CompactTextString(m) }
func (*IMDepartmentReq) ProtoMessage()               {}
func (*IMDepartmentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IMDepartmentReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDepartmentRsp struct {
	// cmd id:		0x0211
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LatestUpdateTime *uint32                     `protobuf:"varint,2,req,name=latest_update_time" json:"latest_update_time,omitempty"`
	DeptList         []*IM_BaseDefine.DepartInfo `protobuf:"bytes,3,rep,name=dept_list" json:"dept_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMDepartmentRsp) Reset()                    { *m = IMDepartmentRsp{} }
func (m *IMDepartmentRsp) String() string            { return proto.CompactTextString(m) }
func (*IMDepartmentRsp) ProtoMessage()               {}
func (*IMDepartmentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *IMDepartmentRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentRsp) GetDeptList() []*IM_BaseDefine.DepartInfo {
	if m != nil {
		return m.DeptList
	}
	return nil
}

func (m *IMDepartmentRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMRecentContactSessionReq)(nil), "IM.Buddy.IMRecentContactSessionReq")
	proto.RegisterType((*IMRecentContactSessionRsp)(nil), "IM.Buddy.IMRecentContactSessionRsp")
	proto.RegisterType((*IMRecentSesAndUnreadCntRsp)(nil), "IM.Buddy.IMRecentSesAndUnreadCntRsp")
	proto.RegisterType((*IMUserStatNotify)(nil), "IM.Buddy.IMUserStatNotify")
	proto.RegisterType((*IMUsersInfoReq)(nil), "IM.Buddy.IMUsersInfoReq")
	proto.RegisterType((*IMUsersInfoRsp)(nil), "IM.Buddy.IMUsersInfoRsp")
	proto.RegisterType((*IMRemoveSessionReq)(nil), "IM.Buddy.IMRemoveSessionReq")
	proto.RegisterType((*IMRemoveSessionRsp)(nil), "IM.Buddy.IMRemoveSessionRsp")
	proto.RegisterType((*IMAllUserReq)(nil), "IM.Buddy.IMAllUserReq")
	proto.RegisterType((*IMAllUserRsp)(nil), "IM.Buddy.IMAllUserRsp")
	proto.RegisterType((*IMUsersStatReq)(nil), "IM.Buddy.IMUsersStatReq")
	proto.RegisterType((*IMUsersStatRsp)(nil), "IM.Buddy.IMUsersStatRsp")
	proto.RegisterType((*IMChangeAvatarReq)(nil), "IM.Buddy.IMChangeAvatarReq")
	proto.RegisterType((*IMChangeAvatarRsp)(nil), "IM.Buddy.IMChangeAvatarRsp")
	proto.RegisterType((*IMPCLoginStatusNotify)(nil), "IM.Buddy.IMPCLoginStatusNotify")
	proto.RegisterType((*IMRemoveSessionNotify)(nil), "IM.Buddy.IMRemoveSessionNotify")
	proto.RegisterType((*IMDepartmentReq)(nil), "IM.Buddy.IMDepartmentReq")
	proto.RegisterType((*IMDepartmentRsp)(nil), "IM.Buddy.IMDepartmentRsp")
}

var fileDescriptor0 = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x95, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x95, 0x15, 0x09, 0x7a, 0x2d, 0xdd, 0xc8, 0x8a, 0xd6, 0x75, 0x2f, 0xa3, 0x4f, 0x05,
	0xa1, 0x82, 0xfa, 0x01, 0x40, 0x5d, 0x27, 0x41, 0xa4, 0x65, 0x9a, 0x56, 0xf6, 0xc0, 0x03, 0xb2,
	0x4c, 0xe2, 0x76, 0x41, 0x89, 0x1d, 0xe2, 0xcb, 0xa4, 0x4a, 0x3c, 0x00, 0xdf, 0x81, 0x8f, 0xc0,
	0xf7, 0xc4, 0x4e, 0x1a, 0xad, 0xcd, 0x9c, 0xc0, 0x50, 0xdf, 0x1a, 0xfb, 0xfc, 0xf3, 0xff, 0xee,
	0xfe, 0xe7, 0x42, 0xc7, 0x71, 0x47, 0x27, 0xa9, 0xef, 0x2f, 0x47, 0x71, 0x22, 0x50, 0xd8, 0x8f,
	0x8a, 0xef, 0xfe, 0xbe, 0xfe, 0x45, 0x25, 0x3b, 0x65, 0xf3, 0x80, 0xb3, 0x7c, 0x7b, 0xf0, 0x09,
	0x0e, 0x1d, 0xf7, 0x92, 0x79, 0x8c, 0xe3, 0x54, 0x70, 0xa4, 0x1e, 0xce, 0x98, 0x94, 0x81, 0xe0,
	0x97, 0xec, 0xab, 0xbd, 0x0b, 0x0f, 0x53, 0xc9, 0x12, 0x12, 0xf8, 0x3d, 0xeb, 0x78, 0x67, 0xf8,
	0xd8, 0xee, 0x83, 0x1d, 0x52, 0x64, 0x12, 0x49, 0x1a, 0xfb, 0xea, 0x07, 0xc1, 0x20, 0x62, 0xbd,
	0x9d, 0x6c, 0x6f, 0x1f, 0x5a, 0x14, 0x15, 0xe0, 0x9a, 0xa8, 0x1d, 0xda, 0xeb, 0x1e, 0x5b, 0xc3,
	0xf6, 0xe0, 0xa7, 0x55, 0xc9, 0x97, 0xf1, 0x5d, 0xfe, 0x5b, 0xe8, 0x7a, 0x79, 0x14, 0x91, 0x79,
	0x18, 0x09, 0x03, 0x89, 0xea, 0x86, 0xc6, 0xb0, 0x35, 0x7e, 0x36, 0xda, 0xcc, 0x60, 0x13, 0xe8,
	0xf0, 0xb9, 0x30, 0x8b, 0xf8, 0x6d, 0x41, 0xbf, 0x10, 0xa1, 0x82, 0x27, 0xdc, 0xbf, 0xe2, 0x09,
	0xa3, 0xfe, 0x94, 0xa3, 0x51, 0xc5, 0xbb, 0x5a, 0x15, 0xcf, 0x2b, 0x55, 0xac, 0x83, 0x33, 0x35,
	0x3d, 0xd8, 0x4b, 0xb3, 0x05, 0x82, 0x02, 0x69, 0x48, 0x3c, 0x8e, 0xbd, 0x46, 0x75, 0xb1, 0xde,
	0xc0, 0x9e, 0xe3, 0x5e, 0x29, 0x29, 0x33, 0xa4, 0x78, 0x2e, 0x30, 0x98, 0x2f, 0xed, 0x17, 0xd0,
	0xcc, 0xc4, 0x49, 0xb5, 0x94, 0xc9, 0x6b, 0x8d, 0x0f, 0x4a, 0x02, 0x8a, 0x13, 0x83, 0x33, 0xdd,
	0x7c, 0xfd, 0x25, 0xf5, 0xed, 0xc6, 0x06, 0x76, 0xa1, 0xbd, 0x5a, 0xb8, 0x4d, 0xa9, 0x42, 0xcd,
	0x62, 0x93, 0x66, 0x2a, 0xd4, 0x2b, 0xe8, 0xe4, 0x0b, 0x2a, 0x60, 0xbd, 0x44, 0x26, 0x85, 0xd5,
	0xed, 0xf9, 0x6e, 0x81, 0xad, 0xdb, 0x13, 0x89, 0x1b, 0x56, 0x67, 0xbe, 0xd7, 0xd0, 0x2e, 0xda,
	0x81, 0xcb, 0x38, 0xb7, 0x5d, 0x67, 0xdc, 0x2f, 0xdd, 0xb5, 0x22, 0x7c, 0x50, 0x11, 0xb6, 0x0d,
	0x50, 0x9c, 0x50, 0x94, 0x9a, 0xca, 0xff, 0x32, 0x48, 0x30, 0x25, 0xac, 0x0e, 0x27, 0x4c, 0xa6,
	0x21, 0x12, 0x4f, 0xf8, 0x85, 0xf1, 0xcb, 0xba, 0x1a, 0xf7, 0xd4, 0xf5, 0xa0, 0x5a, 0xd7, 0x05,
	0xb4, 0x1d, 0x77, 0x12, 0x86, 0xba, 0x80, 0xdb, 0x19, 0xc8, 0x6f, 0xeb, 0x44, 0x53, 0x8a, 0x75,
	0xc4, 0xc2, 0x8c, 0x59, 0xab, 0x1b, 0xff, 0xd1, 0xea, 0x5b, 0x87, 0x6a, 0xc3, 0x6e, 0xcf, 0xa1,
	0x19, 0xad, 0xce, 0xa1, 0x7a, 0x7c, 0xfe, 0xe6, 0x50, 0x0d, 0x31, 0x5f, 0xe4, 0xc2, 0x13, 0xc7,
	0x9d, 0x5e, 0x53, 0xbe, 0x60, 0x93, 0x1b, 0xb5, 0x6c, 0xee, 0x85, 0xea, 0x2a, 0xcd, 0x76, 0x49,
	0x9a, 0x84, 0x59, 0xc5, 0x9a, 0x66, 0xdc, 0xf9, 0x1d, 0xdc, 0x3f, 0x7b, 0xcd, 0xc8, 0xfb, 0x08,
	0x4f, 0x1d, 0xf7, 0x62, 0x7a, 0x26, 0x16, 0x01, 0xd7, 0x49, 0xa4, 0x72, 0xf5, 0x78, 0x18, 0xca,
	0x01, 0xa1, 0x8e, 0xca, 0x9f, 0x93, 0x7c, 0x80, 0x8e, 0x2a, 0x4a, 0xa1, 0x9d, 0x3a, 0xe0, 0x1a,
	0xbd, 0x31, 0x17, 0x55, 0xe8, 0xad, 0x4c, 0xe7, 0x60, 0x06, 0xbb, 0x8e, 0x7b, 0xca, 0x62, 0x9a,
	0x60, 0xa4, 0x5e, 0xeb, 0xed, 0x78, 0xfe, 0x87, 0x55, 0xa2, 0xde, 0xd7, 0xf7, 0x2f, 0xa1, 0xe9,
	0xb3, 0x18, 0xd7, 0x7d, 0x7f, 0x58, 0x4a, 0x2c, 0xa7, 0x57, 0x3a, 0xff, 0xe4, 0x08, 0x0e, 0x3c,
	0x11, 0x8d, 0x22, 0xb1, 0x48, 0xbf, 0x04, 0x6c, 0x84, 0x98, 0xff, 0xff, 0x7e, 0x4e, 0xe7, 0xef,
	0x1b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x56, 0x0a, 0x66, 0x77, 0xb4, 0x07, 0x00, 0x00,
}
