// Code generated by protoc-gen-go.
// source: IM.Login.proto
// DO NOT EDIT!

/*
Package IM_Login is a generated protocol buffer package.

It is generated from these files:
	IM.Login.proto

It has these top-level messages:
	IMMsgServReq
	IMMsgServRsp
	IMLoginReq
	IMAccessTokenLoginReq
	IMLoginRes
	IMLogoutReq
	IMLogoutRsp
	IMKickUser
	IMDeviceTokenReq
	IMDeviceTokenRsp
	IMKickPCClientReq
	IMKickPCClientRsp
*/
package IM_Login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import "IMWebServer/models/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type IMMsgServReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMMsgServReq) Reset()                    { *m = IMMsgServReq{} }
func (m *IMMsgServReq) String() string            { return proto.CompactTextString(m) }
func (*IMMsgServReq) ProtoMessage()               {}
func (*IMMsgServReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IMMsgServRsp struct {
	// cmd id:		0x0102
	ResultCode       *IM_BaseDefine.ResultType `protobuf:"varint,1,req,name=result_code,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	PriorIp          *string                   `protobuf:"bytes,2,opt,name=prior_ip" json:"prior_ip,omitempty"`
	BackipIp         *string                   `protobuf:"bytes,3,opt,name=backip_ip" json:"backip_ip,omitempty"`
	Port             *uint32                   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMMsgServRsp) Reset()                    { *m = IMMsgServRsp{} }
func (m *IMMsgServRsp) String() string            { return proto.CompactTextString(m) }
func (*IMMsgServRsp) ProtoMessage()               {}
func (*IMMsgServRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMMsgServRsp) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMMsgServRsp) GetPriorIp() string {
	if m != nil && m.PriorIp != nil {
		return *m.PriorIp
	}
	return ""
}

func (m *IMMsgServRsp) GetBackipIp() string {
	if m != nil && m.BackipIp != nil {
		return *m.BackipIp
	}
	return ""
}

func (m *IMMsgServRsp) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type IMLoginReq struct {
	// cmd id:		0x0103
	UserName         *string                     `protobuf:"bytes,1,req,name=user_name" json:"user_name,omitempty"`
	Password         *string                     `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	OnlineStatus     *IM_BaseDefine.UserStatType `protobuf:"varint,3,req,name=online_status,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	ClientType       *IM_BaseDefine.ClientType   `protobuf:"varint,4,req,name=client_type,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	DeviceId         *string                     `protobuf:"bytes,5,req,name=device_id" json:"device_id,omitempty"`
	ClientVersion    *string                     `protobuf:"bytes,6,opt,name=client_version" json:"client_version,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMLoginReq) Reset()                    { *m = IMLoginReq{} }
func (m *IMLoginReq) String() string            { return proto.CompactTextString(m) }
func (*IMLoginReq) ProtoMessage()               {}
func (*IMLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMLoginReq) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *IMLoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *IMLoginReq) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMLoginReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *IMLoginReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type IMAccessTokenLoginReq struct {
	// cmd id:		268
	AccessToken      *string                     `protobuf:"bytes,1,req,name=access_token" json:"access_token,omitempty"`
	OnlineStatus     *IM_BaseDefine.UserStatType `protobuf:"varint,2,req,name=online_status,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	ClientType       *IM_BaseDefine.ClientType   `protobuf:"varint,3,req,name=client_type,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	DeviceId         *string                     `protobuf:"bytes,4,opt,name=device_id" json:"device_id,omitempty"`
	ClientVersion    *string                     `protobuf:"bytes,5,opt,name=client_version" json:"client_version,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMAccessTokenLoginReq) Reset()                    { *m = IMAccessTokenLoginReq{} }
func (m *IMAccessTokenLoginReq) String() string            { return proto.CompactTextString(m) }
func (*IMAccessTokenLoginReq) ProtoMessage()               {}
func (*IMAccessTokenLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMAccessTokenLoginReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *IMAccessTokenLoginReq) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMAccessTokenLoginReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMAccessTokenLoginReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *IMAccessTokenLoginReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type IMLoginRes struct {
	// cmd id:		0x0104
	ServerTime       *uint32                     `protobuf:"varint,1,req,name=server_time" json:"server_time,omitempty"`
	ResultCode       *IM_BaseDefine.ResultType   `protobuf:"varint,2,req,name=result_code,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	ResultString     *string                     `protobuf:"bytes,3,opt,name=result_string" json:"result_string,omitempty"`
	OnlineStatus     *IM_BaseDefine.UserStatType `protobuf:"varint,4,opt,name=online_status,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	UserInfo         *IM_BaseDefine.UserInfo     `protobuf:"bytes,5,opt,name=user_info" json:"user_info,omitempty"`
	AccessToken      *string                     `protobuf:"bytes,6,opt,name=access_token" json:"access_token,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMLoginRes) Reset()                    { *m = IMLoginRes{} }
func (m *IMLoginRes) String() string            { return proto.CompactTextString(m) }
func (*IMLoginRes) ProtoMessage()               {}
func (*IMLoginRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IMLoginRes) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *IMLoginRes) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMLoginRes) GetResultString() string {
	if m != nil && m.ResultString != nil {
		return *m.ResultString
	}
	return ""
}

func (m *IMLoginRes) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginRes) GetUserInfo() *IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *IMLoginRes) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

type IMLogoutReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMLogoutReq) Reset()                    { *m = IMLogoutReq{} }
func (m *IMLogoutReq) String() string            { return proto.CompactTextString(m) }
func (*IMLogoutReq) ProtoMessage()               {}
func (*IMLogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type IMLogoutRsp struct {
	// cmd id:		0x0106
	ResultCode       *uint32 `protobuf:"varint,1,req,name=result_code" json:"result_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMLogoutRsp) Reset()                    { *m = IMLogoutRsp{} }
func (m *IMLogoutRsp) String() string            { return proto.CompactTextString(m) }
func (*IMLogoutRsp) ProtoMessage()               {}
func (*IMLogoutRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMLogoutRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

type IMKickUser struct {
	// cmd id:		0x0107
	UserId           *uint32                       `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	KickReason       *IM_BaseDefine.KickReasonType `protobuf:"varint,2,req,name=kick_reason,enum=IM.BaseDefine.KickReasonType" json:"kick_reason,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *IMKickUser) Reset()                    { *m = IMKickUser{} }
func (m *IMKickUser) String() string            { return proto.CompactTextString(m) }
func (*IMKickUser) ProtoMessage()               {}
func (*IMKickUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMKickUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickUser) GetKickReason() IM_BaseDefine.KickReasonType {
	if m != nil && m.KickReason != nil {
		return *m.KickReason
	}
	return IM_BaseDefine.KickReasonType_KICK_REASON_DUPLICATE_USER
}

type IMDeviceTokenReq struct {
	// cmd id:		0x0108
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	DeviceToken      *string                   `protobuf:"bytes,2,req,name=device_token" json:"device_token,omitempty"`
	ClientType       *IM_BaseDefine.ClientType `protobuf:"varint,3,opt,name=client_type,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMDeviceTokenReq) Reset()                    { *m = IMDeviceTokenReq{} }
func (m *IMDeviceTokenReq) String() string            { return proto.CompactTextString(m) }
func (*IMDeviceTokenReq) ProtoMessage()               {}
func (*IMDeviceTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMDeviceTokenReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenReq) GetDeviceToken() string {
	if m != nil && m.DeviceToken != nil {
		return *m.DeviceToken
	}
	return ""
}

func (m *IMDeviceTokenReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMDeviceTokenReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDeviceTokenRsp struct {
	// cmd id: 		0x0109
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDeviceTokenRsp) Reset()                    { *m = IMDeviceTokenRsp{} }
func (m *IMDeviceTokenRsp) String() string            { return proto.CompactTextString(m) }
func (*IMDeviceTokenRsp) ProtoMessage()               {}
func (*IMDeviceTokenRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMDeviceTokenRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 只给移动端请求
type IMKickPCClientReq struct {
	// cmd id:		0x010a
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickPCClientReq) Reset()                    { *m = IMKickPCClientReq{} }
func (m *IMKickPCClientReq) String() string            { return proto.CompactTextString(m) }
func (*IMKickPCClientReq) ProtoMessage()               {}
func (*IMKickPCClientReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMKickPCClientReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type IMKickPCClientRsp struct {
	// cmd id: 		0x010b
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code" json:"result_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickPCClientRsp) Reset()                    { *m = IMKickPCClientRsp{} }
func (m *IMKickPCClientRsp) String() string            { return proto.CompactTextString(m) }
func (*IMKickPCClientRsp) ProtoMessage()               {}
func (*IMKickPCClientRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMKickPCClientRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickPCClientRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func init() {
	proto.RegisterType((*IMMsgServReq)(nil), "IM.Login.IMMsgServReq")
	proto.RegisterType((*IMMsgServRsp)(nil), "IM.Login.IMMsgServRsp")
	proto.RegisterType((*IMLoginReq)(nil), "IM.Login.IMLoginReq")
	proto.RegisterType((*IMAccessTokenLoginReq)(nil), "IM.Login.IMAccessTokenLoginReq")
	proto.RegisterType((*IMLoginRes)(nil), "IM.Login.IMLoginRes")
	proto.RegisterType((*IMLogoutReq)(nil), "IM.Login.IMLogoutReq")
	proto.RegisterType((*IMLogoutRsp)(nil), "IM.Login.IMLogoutRsp")
	proto.RegisterType((*IMKickUser)(nil), "IM.Login.IMKickUser")
	proto.RegisterType((*IMDeviceTokenReq)(nil), "IM.Login.IMDeviceTokenReq")
	proto.RegisterType((*IMDeviceTokenRsp)(nil), "IM.Login.IMDeviceTokenRsp")
	proto.RegisterType((*IMKickPCClientReq)(nil), "IM.Login.IMKickPCClientReq")
	proto.RegisterType((*IMKickPCClientRsp)(nil), "IM.Login.IMKickPCClientRsp")
}

var fileDescriptor0 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x55, 0xfe, 0xf4, 0xf7, 0x6b, 0x26, 0x71, 0x68, 0x9d, 0x16, 0xcc, 0x3f, 0xa9, 0xb2, 0x38,
	0x54, 0x1c, 0x7c, 0xc8, 0x09, 0x8e, 0xb4, 0x3d, 0x60, 0x81, 0x25, 0x48, 0xcb, 0x79, 0xb5, 0xb5,
	0x37, 0x61, 0x49, 0xba, 0xeb, 0xee, 0xae, 0x83, 0xca, 0x81, 0x4f, 0xc6, 0x81, 0x4f, 0xc2, 0x67,
	0x61, 0x76, 0xd7, 0xa0, 0x60, 0x07, 0xaa, 0xde, 0x32, 0xb3, 0xcf, 0xf3, 0xde, 0x9b, 0x79, 0x0a,
	0x8c, 0xd3, 0x2c, 0x79, 0x2b, 0x17, 0x5c, 0x24, 0xa5, 0x92, 0x46, 0x86, 0xbb, 0xbf, 0xea, 0x47,
	0x13, 0xfc, 0x75, 0x42, 0x35, 0x3b, 0x63, 0x73, 0x2e, 0x98, 0x7f, 0x8e, 0xc7, 0x30, 0x4a, 0xb3,
	0x4c, 0x2f, 0xce, 0x99, 0x5a, 0xcf, 0xd8, 0x75, 0x7c, 0xbd, 0x59, 0xeb, 0x32, 0x4c, 0x60, 0xa8,
	0x98, 0xae, 0x56, 0x86, 0xe4, 0xb2, 0x60, 0x51, 0xe7, 0xa8, 0x7b, 0x3c, 0x9e, 0x3e, 0x4c, 0xfe,
	0x1c, 0x35, 0x73, 0x88, 0x8b, 0x9b, 0x92, 0x85, 0x7b, 0xb0, 0x5b, 0x2a, 0x2e, 0x15, 0xe1, 0x65,
	0xd4, 0x3d, 0xea, 0x1c, 0x0f, 0xc2, 0x7d, 0x18, 0x5c, 0xd2, 0x7c, 0xc9, 0x4b, 0xdb, 0xea, 0xb9,
	0xd6, 0x08, 0xfa, 0xa5, 0x54, 0x26, 0xea, 0x63, 0x15, 0xc4, 0xdf, 0x3b, 0x00, 0x69, 0xe6, 0x34,
	0xa2, 0x02, 0x8b, 0xaf, 0x34, 0x53, 0x44, 0xd0, 0x2b, 0xcf, 0x37, 0x70, 0x43, 0xa9, 0xd6, 0x9f,
	0xa5, 0x2a, 0x70, 0xa8, 0xed, 0x4c, 0x21, 0x90, 0x62, 0x85, 0xdc, 0x44, 0x1b, 0x6a, 0x2a, 0x8d,
	0x83, 0xad, 0xb0, 0xc7, 0x0d, 0x61, 0x1f, 0x70, 0xd0, 0x39, 0x02, 0x9c, 0x34, 0xb4, 0x92, 0xaf,
	0x38, 0x13, 0x86, 0x18, 0x2c, 0x91, 0x7c, 0x9b, 0x95, 0x53, 0x87, 0x70, 0x78, 0x14, 0x52, 0xb0,
	0x35, 0xcf, 0x19, 0xe1, 0x45, 0xb4, 0xe3, 0x68, 0xef, 0xc3, 0xb8, 0x1e, 0xb1, 0x66, 0x4a, 0x73,
	0x29, 0xa2, 0xff, 0xac, 0xa1, 0xf8, 0x5b, 0x07, 0x0e, 0xd3, 0xec, 0x55, 0x9e, 0x33, 0xad, 0x2f,
	0xe4, 0x92, 0x89, 0xdf, 0x6e, 0x0e, 0x60, 0x44, 0x5d, 0x9b, 0x18, 0xdb, 0xaf, 0x0d, 0xb5, 0xe4,
	0x77, 0xef, 0x2c, 0xbf, 0x77, 0x27, 0xf9, 0x7d, 0xb7, 0xf7, 0xb6, 0xfc, 0x1d, 0x27, 0xff, 0xc7,
	0xe6, 0x05, 0x74, 0x38, 0x81, 0x21, 0x12, 0x23, 0x84, 0x18, 0x5e, 0xdf, 0x20, 0x68, 0x06, 0xa1,
	0x7b, 0x5b, 0x10, 0x0e, 0x21, 0xa8, 0xf1, 0xda, 0x28, 0x2e, 0x16, 0xf5, 0xe9, 0x5b, 0xce, 0xad,
	0xb2, 0x5b, 0x9c, 0x3f, 0xaf, 0x13, 0xc1, 0xc5, 0x5c, 0x3a, 0xc5, 0xc3, 0xe9, 0x83, 0x2d, 0xf8,
	0x14, 0x9f, 0x5b, 0xfb, 0xf6, 0xf7, 0x09, 0x60, 0xe8, 0xfc, 0xc9, 0xca, 0xd8, 0x90, 0xc7, 0x1b,
	0x25, 0x66, 0x7c, 0xd2, 0xce, 0x78, 0x10, 0xbf, 0xb7, 0x2b, 0x79, 0xc3, 0xf3, 0xa5, 0x1d, 0x1d,
	0xde, 0x83, 0xff, 0xbd, 0x84, 0xa2, 0x5e, 0xc7, 0x14, 0x86, 0x4b, 0x7c, 0x24, 0x8a, 0x51, 0x8d,
	0x7b, 0xf4, 0xeb, 0x78, 0xda, 0x50, 0x65, 0x3f, 0x9f, 0x39, 0x80, 0xf5, 0x11, 0x7f, 0x85, 0xbd,
	0x34, 0x3b, 0x73, 0x37, 0x71, 0x21, 0xb1, 0xf9, 0x68, 0x0d, 0x46, 0x03, 0xf5, 0xd9, 0xbc, 0x01,
	0x9f, 0xf7, 0xd6, 0xf1, 0x3b, 0xff, 0x3e, 0x3e, 0x5a, 0xa2, 0xc6, 0xd0, 0xfc, 0x23, 0x29, 0xa8,
	0xa1, 0xd1, 0x01, 0xe2, 0x47, 0xf1, 0x8b, 0x26, 0x3f, 0x7a, 0x6f, 0xf1, 0x6f, 0xfd, 0xf2, 0x19,
	0xec, 0xfb, 0x65, 0xbc, 0x3b, 0xf5, 0x24, 0xdb, 0xa4, 0xc7, 0x2f, 0x5b, 0xa8, 0xbf, 0x10, 0x34,
	0x83, 0x14, 0x9c, 0x3c, 0x81, 0x28, 0x97, 0x57, 0xc9, 0x4d, 0x25, 0xbe, 0x54, 0x9f, 0x38, 0x4d,
	0x8c, 0xf1, 0xff, 0x4f, 0x97, 0xd5, 0xfc, 0x75, 0xef, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd,
	0x29, 0x40, 0x5d, 0xd4, 0x04, 0x00, 0x00,
}
